# Generated by Django 3.0.5 on 2021-06-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrulla', models.CharField(max_length=10, verbose_name='Numero de patrulla')),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo del policia')),
                ('lugar', models.CharField(max_length=50, verbose_name='Lugar del incidente')),
                ('incidente', models.TextField(verbose_name='Detalles de incidente')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fehca del incidente')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
    ]
