# Generated by Django 3.0.5 on 2021-06-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='foto',
            field=models.ImageField(default='null', upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del incidente'),
        ),
    ]
