# Generated by Django 3.0.5 on 2021-06-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210615_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('desc', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('Lng', models.FloatField(verbose_name='Longitud')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Punto',
                'verbose_name_plural': 'Puntos',
            },
        ),
        migrations.AlterField(
            model_name='reporte',
            name='foto',
            field=models.ImageField(default='null', upload_to='reportes', verbose_name='Foto'),
        ),
    ]
